# Generated by Django 5.0.4 on 2025-07-29 11:18

import DMS_MDT.models
import django.db.models.deletion
import django_enumfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_web', '0005_remove_dms_user_user_contact_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_version',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('os_version', models.CharField(max_length=9, null=True)),
                ('device_platform', django_enumfield.db.fields.EnumField(enum=DMS_MDT.models.device_platform, null=True)),
                ('app_version', models.CharField(max_length=9, null=True)),
                ('device_timezone', models.CharField(max_length=50, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('device_token', models.TextField(null=True)),
                ('model_name', models.CharField(max_length=200, null=True)),
                ('status', django_enumfield.db.fields.EnumField(default=1, enum=DMS_MDT.models.status_enum, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device_version_info',
            fields=[
                ('device_version_id', models.AutoField(primary_key=True, serialize=False)),
                ('os_name', django_enumfield.db.fields.EnumField(enum=DMS_MDT.models.device_platform, null=True)),
                ('os_version', models.CharField(max_length=100, null=True)),
                ('app_location', models.URLField(max_length=500, null=True)),
                ('app_current_version', models.CharField(max_length=50, null=True)),
                ('app_compulsory_version', models.CharField(max_length=50, null=True)),
                ('status', django_enumfield.db.fields.EnumField(default=1, enum=DMS_MDT.models.status_enum)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehical',
            fields=[
                ('veh_id', models.AutoField(primary_key=True, serialize=False)),
                ('veh_number', models.CharField(max_length=50, null=True, unique=True)),
                ('veh_default_mobile', models.CharField(max_length=15, null=True)),
                ('veh_hash', models.TextField(null=True)),
                ('veh_app_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('veh_app_log', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('veh_gps_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('veh_gps_log', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('veh_address', models.TextField(null=True)),
                ('status', django_enumfield.db.fields.EnumField(default=1, enum=DMS_MDT.models.status_enum, null=True)),
                ('vehis_login', models.BooleanField(default=False)),
                ('veh_added_by', models.CharField(max_length=100, null=True)),
                ('veh_added_date', models.DateTimeField(auto_now_add=True)),
                ('veh_modify_by', models.CharField(max_length=100, null=True)),
                ('veh_modify_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('veh_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_city')),
                ('veh_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_district')),
                ('veh_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_state')),
                ('veh_tahsil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_tahsil')),
                ('veh_ward_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_ward')),
            ],
        ),
        migrations.CreateModel(
            name='incident_vehicle',
            fields=[
                ('inc_veh_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', django_enumfield.db.fields.EnumField(default=1, enum=DMS_MDT.models.status_enum, null=True)),
                ('added_by', models.CharField(max_length=100, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('modify_by', models.CharField(max_length=100, null=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('dep_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_department')),
                ('incident_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_incident')),
                ('veh_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DMS_MDT.vehical', to_field='veh_number')),
            ],
        ),
        migrations.CreateModel(
            name='employee_clockin_info',
            fields=[
                ('emp_clockin_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_clockin_time', models.DateTimeField(null=True)),
                ('emp_clockout_time', models.DateTimeField(null=True)),
                ('status', django_enumfield.db.fields.EnumField(default=1, enum=DMS_MDT.models.status_enum, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('clock_out_in_status', django_enumfield.db.fields.EnumField(default=1, enum=DMS_MDT.models.check_in_out_status, null=True)),
                ('emp_image', models.FileField(null=True, upload_to='media_files/Mdt_employee/')),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_employee')),
                ('veh_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DMS_MDT.vehical')),
            ],
        ),
        migrations.CreateModel(
            name='Vehical_base_location',
            fields=[
                ('bs_id', models.AutoField(primary_key=True, serialize=False)),
                ('bs_name', models.CharField(max_length=100)),
                ('bs_address', models.TextField(null=True)),
                ('bs_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('bs_long', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('status', django_enumfield.db.fields.EnumField(default=1, enum=DMS_MDT.models.status_enum, null=True)),
                ('bs_added_by', models.CharField(max_length=200, null=True)),
                ('bs_added_date', models.DateTimeField(auto_now_add=True)),
                ('bs_modify_by', models.CharField(max_length=200, null=True)),
                ('bs_modify_date', models.DateTimeField(auto_now=True)),
                ('bs_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_city')),
                ('bs_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_district')),
                ('bs_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_state')),
                ('bs_tahsil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_tahsil')),
                ('bs_ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_web.dms_ward')),
            ],
        ),
        migrations.AddField(
            model_name='vehical',
            name='veh_base_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DMS_MDT.vehical_base_location'),
        ),
        migrations.CreateModel(
            name='vehicle_login_info',
            fields=[
                ('veh_login_id', models.AutoField(primary_key=True, serialize=False)),
                ('veh_login_time', models.DateTimeField(null=True)),
                ('veh_logout_time', models.DateTimeField(null=True)),
                ('status', django_enumfield.db.fields.EnumField(default=1, enum=DMS_MDT.models.status_enum, null=True)),
                ('clock_out_in_status', django_enumfield.db.fields.EnumField(default=1, enum=DMS_MDT.models.check_in_out_status, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('device_id', models.IntegerField(null=True)),
                ('veh_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DMS_MDT.vehical')),
            ],
        ),
    ]
